### ISSUE TITLE
trying to help with centos8

### ISSUE THREAD

**Issue by jlabegg** [Zer0CoolX/guacamole-install-rhel-7#135]
A great thank to the hard work with this beautifull script.
I tried to adapt this script to centos8.
Being short of time, and judging by the end of support of centos7, i think i'll use centos7 to achieve my immediate duties.
However, the test i've made could be of some use for others to achieve the adaptation of this script to centos8.
I've worked on the different dependencies.
this is how i managed .

dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm

yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/libssh2-1.8.0-3.el7.x86_64.rpm
yum -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/libssh2-devel-1.8.0-3.el7.x86_64.rpm
yum -y install http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/l/libtelnet-0.21-5.el7.x86_64.rpm
yum -y install http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/l/libtelnet-devel-0.21-5.el7.x86_64.rpm
yum install -y --enablerepo=PowerTools freerdp-devel
yum install -y --enablerepo=PowerTools libvncserver-devel
yum install -y --enablerepo=PowerTools libvorbis-devel
yum install -y --enablerepo=PowerTools uuid-devel
yum install -y ffmpeg-devel --enablerepo=PowerTools
yum install -y libwebsockets-devel --enablerepo=Devel
yum install -y policycoreutils-python-utils

One of the trouble with the install of policycoreutils-python is that passig from el7 to el8, the name have changed: now it's policycoreutils-python-utils

Of course, we need to install those dependencies before launching the script.
And to modify some parts of the line 1048 of the script: policycoreutils-python => policycoreutils-python-utils and wipe tomcat because you have to install tomcat manually before launching the script

By doing this, you should fulfill the dependencies.

The last piece of work is with tomcat...
The passage from el7 to el8 have changed some of the directories... 
in el7, the installation of guacamole jars where in /usr/share/tomcat/.....
in el8, the installation path is /opt/tomcat/...

Hope this could help.

And thanks again

(sorry, this is not really an issue, but i didn't foud the button suggestion/comment)

**Comment by Zer0CoolX** [comment]
Hello and thank you for the info and offer to help. I am also glad you find the current script useful.

I have actually been doing a lot of work "behind the scenes" on a RHEL/CentOS 8 version of this script. I am at the point I can do a "basic" install using a self signed cert and database only authentication. I still have some work to do on more advanced configs like LDAP, Lets Encrypt, 2FA, etc.

I have not posted the script yet as its not ready to be used and I don't want people (regardless of what disclaimers I could put in the repo/readme) to attempt using it in production. I am also trying many things which having commits for would just end up being "noise", IE: trying various things out to fix a problem that may or may not work.

I was hoping to have something ready by now but the truth is its becoming harder for me to find free time to work on it. I get a day here and a weekend there with sometimes weeks between them.

Additionally much has changed since I first wrote the script; so I essentially re-wrote large portions of the script. Tweaking things, improving security, reviewing how I handle certain tasks, etc. which of course has made the process slower. Thats beyond "just" updating it for RHEL/CentOS 8.

If you are interested in testing the RHEL/CentOS 8 version of the script I would be happy to send it to you (and its ok if your not). I can reply to this topic with my email address (so you can email me and not share your email publicly) or you can provide me an address to send it to. The only thing(s) I ask: Don't post it publicly and provide me as much feedback/detail as you can to improve/fix/finish it. Testing things like; LDAP(s), 2FA, Let's Encrypt, different Nginx/security settings, etc would be very helpful.

Thank you again for your interest and input.

**Comment by jlabegg** [comment]
Hello, and thank you for your kind answer.
I understand your point and agree with your arguments.
If I may be of some help, I'd be glad to lend a (small) hand.
Today, I've used your script on centos7. My purpose was to upgrade from an
installation version 0.9.12.
New VM, backed up the database from the ancient server, installed and
launched your script, restored the db, upgraded the db version
That worked well, I've even had time to enhance it with the 2FA and your
branding.
That gave me time to test different setups with the 2FA... sha1 worked like
a charm, but no sha256 or sha512.
I tweaked the self signing certificate aging too (1 year is a bit short, 10
years is more 'secure'... if you forget to renew your certificate, users
may be quite angry to discover they can't connect any more), and, after
all, behind a reverse proxy, this certificate is less important to follow.
For nginx/security settings, i'm afraid i'll be of almost no help: my
guacamole lies behind a pfsense firewall, to enhance security.
I'll have to conduct some basic pentests on it, from the outside (that
would be pfsense security) and from the inside (nginx, until i put ae
pfsense between with a bridge).
So, if you want, I'm ok to conduct some tests, on some conditions:
I can't assume accurate delays (my first duty is for my family, my second
for my work, the rest comes third...)
To be efficient, we need to have some rules to conduct those tests; you're
the boss, you tell me what to do and what kind of information you want back
and I feed back those information and whatever thoughts I have.
I'm ok to exchange on email.

Once again, thank you for your hard work and sharing.

**Comment by fachex** [comment]
I would gladly try the "beta" scrip for CentOS 8. The RHEL 7 script is by far the best script we found to install Guacamole. The problem that we face is that MacOS and iOS (grrrr) require TomCat 8+ to work. We have been trying to update the script to use at least RHEL 7 with TomCat 8 but we have not been successful. 
I appreciate all your work.

**Comment by Zer0CoolX** [comment]
@jlabegg Glad to hear it has worked out for you. For TOTP most authenticators do not yet support sha256 or sha512, only sha1 6 digits. I would confirm that the authenticator you use does in fact supports those modes (for example I use Authy and at the time I checked it only supported sha1).

@fachex I appreciate the praise. When you mean MacOS and iOS working do you mean being able to create connections to them via guacamole or using them to access the web GUI and connect to other things? I ask as I have tested with iOS/Safari and connecting to a Win10 machine using RDP and that works as is. Also a short background is I always aim to use the packages from official repos (or at least trusted repos) when possible, making updates easier. In RHEL/CentOS 7 I pull Tomcat 7 from the official repo.

In my new script for RHEL/CentOS 8, I am "installing" Tomcat 9 from Apache's site as RHEL removed the Tomcat package from the official repos. More of a pain to get and keep updated, however means we can use a more recent version.

@ both of you guys, and anyone else who is willing to test the very early "beta" script, feel free to email me at:
zer0coolxcode
@ gmail.com
(split 2 lines above to make it harder for bots to catch the email and spam me...)
Only 3 requirements I ask:

-  Post in this thread stating in short that you would like to be given the test code (all those above this post have done this already)
- Agree not to publicly share the code with others. This includes giving it to others to test, claiming it as your own and posting it, etc.
- To the best of your ability, test various options and report back findings via an open issue here as I do not regularly check the email account above. This will also make the findings available for others.

I will send the code as a .txt attachment. Change the file extension to `.sh` before using, otherwise follow the same basic steps for running the script as the 7 version after the download step...IE: make it executable, execute script, follow on screen prompts.

As for methodology of testing, do what makes sense to you. This way you may try things I would not think of trying. Just keep track of what selections you made, error messages, workarounds, suggestions, etc. I would just remind everyone this script is still meant to run on a clean RHEL/CentOS install, not over top of an existing Guac install. Best bet would be a VM, snapshot before running new script, restore snapshot to try again.

The interest in this may help motivate me to invest more time and get this working faster allowing me to make it publicly available and hopefully benefiting others. Thanks

**Comment by Zer0CoolX** [comment]
I have responded to your emails with the "beta" code for RHEL/CentOS 8. Looking forward to seeing how it works for you guys. Thanks

**Comment by Zer0CoolX** [comment]
I am closing this issue for the time being as there has not been any feedback posted to it. If needed a new topic can be opened or this may be re-opened in the future.
