### ISSUE TITLE
[BUG] Script Fails if Guacamole Download Fails

### ISSUE THREAD

**Issue by ColinOppenheim** [Zer0CoolX/guacamole-install-rhel-7#140]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y/N
2. You have read the wiki and followed its guidelines including requirements, troubleshooting, etc.? Y

**Details**
OS/Version: RHEL 7.8
Guacamole Source: Stable/Git? Stable
Any other options selected from the script prompts: None

**Describe the bug**
I had to rerun the script cause it failed to download guacamole. It timed out on the mirror server that Apache had provided. Regardless, it failed at making the directories cause they already existed. I inspected your script and I see that you have it set to remove the directories that it creates encase they already exist with variable: {INSTALL_DIR}. However, a closer inspection of your code does not seem to indicate the definition of INSTALL_DIR which would explain why it fails to remove the directories before creating them. I'm guessing in a previous version that was defined somewhere and now it isn't.

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
%%% Error (Script Failed) | Line 1077 | Command: mkdir -v /etc/guacamole | Exit code: 1 %%%

**To Reproduce**
Install and then run the installer again

**Have You Found a Solution to the Issue?**
Need to fix Variable decleration

**Comment by ColinOppenheim** [comment]
I know you have it in your instructions NOT to rerun the script. But it failed at the most basic point. Obviously your code at one point accounted for this issue but that doesn't seem to be working due to that missing variable definition.

**Comment by bechtle-simon-mueller** [comment]
Just change the line so that it does a `mkdir -pv` and this particular error is a goner. 😎

**Comment by Zer0CoolX** [comment]
Thank you for posting, I do appreciate the feedback. A few points to touch on:

- **Why it failed**: This happens rarely when the URL for a mirror times out, is down, your internet has a hiccup, etc. Having run the script many thousands of times myself in testing and using it, I can easily say this is a fraction of 1% of the time. Its so nominal that I have not even mentioned it/documented it.

In the event of the above, my advice and directions essentially make it a none issue...the script should be tested by a person first in an environment were failure, trial & error and eventually confirmation of success can all take place. I usually recommend a VM, taking a snapshot before running the script and then reverting back if it fails. I detail this process in the wiki page for "Testing Procedure".

- **The script is NOT meant to be re-run:** Regardless of what the code itself may infer, I try to be as plain and direct about this as possible. I don't code with the notion of re-running it. Its an intentional choice on my part to not offer it as or try and make it survive failure. Primarily, because in doing so I would also open the door to people intentionally ignoring my other simple direction that its meant to be installed fresh on a clean system not loaded up with a bunch of other stuff. As soon as I start cleaning up after my script I risk wiping out other stuff on existing systems when people ignore my directions.

- **What you found:** I appreciate this part especially. While there was never a time or intention on my part for what you found to do any sort of cleanup from a bad run I see how it could seem that way. The lines removing the folder I install to was likely something I thought was (and in some cases is) good practice (maybe to avoid an error, etc). In hindsight for this particular case, its really something I should remove the lines that delete the install folder on line 1076. INSTALL_DIR is a variable composed of a static path combined with a variable for the GUAC_VER on line 156.

For /etc/guacamole I just never got around to making a variable for it, though again in hindsight it would likely be a good idea since its used various times (albeit statically). However, I wouldn't then add more lines to cleanup this dir or others, it would just be to make it easier to change that path if it needed to be changed.

- **So What's the Solution:** The solution here is really for me to cleanup my code by removing the line to delete the INSTALL_DIR as it should NEVER be required. Again, as per my directions, in the extremely rare case the download fails the OS should be restored from snapshot or the machine re-imaged before trying the script. Long term a better solution would be for me to check that the package downloaded and if not try x times more as this would completely circumvent the "why" i explained early.

Too much else happens prior to the download failing to revert back without again opening the door to losing data or breaking other things someone using the script incorrectly could have happen. For example many packages are installed by my script before the download of Guac, many could be required for other programs someone might have installed (even tho I say do this on a clean system). As is, the script may just fail and their stuff still works. If I change the script to remove the packages I may end up removing something like a repo or specific package their existing software requires, thus breaking what they had.

So really the variables declared are not the issue. The script is not meant under any circumstance to be re-run. The issue you experienced was like winning a bad lottery, just bad luck that statistically has an almost negligible chance to happen. Your input however has helped me identify a way in which I could improve the script and handle that rare issue so it doesn't ruin the experience for others. I cant promise when I can make the changes to fix the matter but eventually I will.

Thanks

**Comment by ColinOppenheim** [comment]
It's not a problem. I'm running it on a VM so there are a number of issues I have had to restore snapshots on. The second time I ran it I had no issues downloading guacamole. It now fails at the process of calling the keystore. I'm an intermediate in Linux at best and I am still learning programming in bash. My linux knowledge is enough to help troubleshoot my problems, just not enough to _efficiently_ solve them.  

My comment is by no means a complaint I know a thing or two about scripting and sysadmin and there are tons of scenarios that you can never plan for until they happen and I agree that rolling it backwards would be quite difficult considering the amount of changes your script makes.  Also, kudos to your detail and commenting in your script. Its something I often strive for myself. I make the effort to my comments like it's going to be read by a 10 year old kid learning coding for the first time.

As I mentioned the script now fails on the function to create the Java Keystore. The issue is my VM does not have Java's location populated in PATH and JAVA_HOME.  Java 1.8 is installed, but ff I run java it just goes and says command not found. Don't know why Oracle doesn't automatically add that path upon installation of the package but that would be one of a thousands complaints i can make towards Oracle. I'd rather fix the script so it works every time, rather than manually fix the problem. I'd like to develop a command to verify Java is in PATH and then if it isn't it use the find command to find the path, add it to $PATH and then move on with the proccess.

**Comment by Zer0CoolX** [comment]
Hello @ColinOppenheim, no worries I just wanted to explain for you and others why what happened, happened. I appreciate you and others providing useful feedback like this to help improve the script for others.

I am gonna close this issue as I think short term I will remove the rm rf line and long term put a check in for the download to prevent failure on the rare failure to download and have it retry.

Would you be kind enough to open a new issue as a help request and fill it out as completely as you can so I may help you resolve the issues running it?

The more specific detail you can provide there the easier it will be to help you. I need to know what options you picked, what error message(s) if any you got, any meaningful log output, etc. to best help. Thanks
